export { default as Layout } from "./Layout";
export { default as Hero } from "./Hero";
export { default as About } from "./About";
export { default as Services } from "./Services";
export { default as Skills } from "./Skills";
export { default as StickyImg } from "./StickyImg";
export { default as Projects } from "./Projects";
export { default as Achieves } from "./Achieves";
export { default as Team } from "./Team";
export { default as Testimonials } from "./Testimonials";
export { default as News } from "./News";
export { default as Clients } from "./Clients";
export * from "./contact";
